name: BotConnector
version: ${project.version}
main: com.github.hank9999.botconnector.BotConnector
api-version: 1.15
authors: [ hank9999 ]
description: Connect your server with the bot program via WebSocket
website: https://github.com/hank9999/BotConnector
